[tool.poetry]
name = "mha-based-fsgnn"
version = "0.1.0"
description = ""
authors = ["Arda Can Aras <ardaaras99@gmail.com>"]
readme = "README.md"
packages = [{ include = "mha_based_fsgnn" }]

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
torch-geometric = "^2.3.1"
torch = "2.0.0"
matplotlib = "^3.7.2"
ipykernel = "^6.25.1"
torchvision = "0.15.1"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
