wandb_version: 1

dataset:
  desc: null
  value:
    dataset_name: Cora
    max_hop: 3
mha:
  desc: null
  value:
    fan_in: 64
    fan_out: 64
    p: 0.4
mlp:
  desc: null
  value:
    dropout: 0.6
    hidden_dims: 300
    out_dim: 64
optimizer:
  desc: null
  value:
    lr: 0.001
    weight_decay: 0.0005
trainer_pipeline:
  desc: null
  value:
    max_epochs: 500
    patience: 50
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696097397.515149
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.11.4
      5: 0.15.11
      8:
      - 4
      - 5
      13: darwin-arm64
