method: grid
project: mha-based-fsgnn
metric:
  name: test/test_accuracy
  goal: maximize
parameters:
  patience:
    value: 100
  max_epochs:
    value: 500
  dataset_name:
    value: "Cora"
  # Optimizer CONFIG
  lr:
    value: 0.1
  wd:
    value: 0.0005
  momentum:
    value: 0.9

# TODO: You can also use hyperband early stopping, check the details from wandb documentation
  